# Generated by Django 6.0.7 on 2026-07-28 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60, unique=True, verbose_name='Nom / Numéro')),
                ('capacite', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Capacité')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CreneauHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.PositiveSmallIntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi')], verbose_name='Jour')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('libelle', models.CharField(blank=True, help_text='Ex : « 08h00–09h00 ». Généré automatiquement si vide.', max_length=60, verbose_name='Libellé')),
            ],
            options={
                'verbose_name': 'Créneau horaire',
                'verbose_name_plural': 'Créneaux horaires',
                'ordering': ['jour', 'heure_debut'],
                'unique_together': {('jour', 'heure_debut', 'heure_fin')},
            },
        ),
        migrations.CreateModel(
            name='SeanceHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='classes.anneescolaire', verbose_name='Année scolaire')),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='planning.creneauhoraire', verbose_name='Créneau')),
                ('matiere_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='subjects.matiereclasse', verbose_name='Matière / Classe')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='planning.salle', verbose_name='Salle')),
            ],
            options={
                'verbose_name': 'Séance horaire',
                'verbose_name_plural': 'Séances horaires',
                'ordering': ['creneau__jour', 'creneau__heure_debut'],
            },
        ),
    ]
