# Generated by Django 6.0.7 on 2026-07-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneauhoraire',
            name='type_creneau',
            field=models.CharField(choices=[('cours', 'Cours'), ('repos', 'Repos / Pause'), ('recreation', 'Récréation'), ('priere', 'Prière / Recueillement'), ('repas', 'Repas')], default='cours', help_text="'Repos' bloque la case dans la grille sans permettre d'y affecter un cours.", max_length=20, verbose_name='Type'),
        ),
    ]
