# Generated by Django 5.2.3 on 2026-07-26 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=9, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('cloturee', models.BooleanField(default=False, verbose_name='Clôturée')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('date_cloture', models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture')),
            ],
            options={
                'verbose_name': 'Année scolaire',
                'verbose_name_plural': 'Années scolaires',
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='JournalOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('CREATION_ANNEE', "Création d'une année"), ('ACTIVATION_ANNEE', "Activation d'une année"), ('CLOTURE_ANNEE', "Clôture d'une année"), ('MIGRATION', 'Migration des données'), ('PROMOTION', 'Promotion des élèves'), ('ARCHIVAGE', 'Archivage'), ('ACTIVATION_SEMESTRE', "Activation d'un semestre"), ('PUBLICATION_SEMESTRE', "Publication d'un semestre")], max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Journal d'opération",
                'verbose_name_plural': 'Journal des opérations',
                'ordering': ['-date_operation'],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('ordre', models.PositiveIntegerField(default=0, help_text='Utilisé pour la promotion automatique. Ordre croissant = niveaux successifs.', verbose_name='Ordre de promotion')),
                ('cycle', models.CharField(blank=True, help_text='Optionnel: Primaire, Secondaire, etc.', max_length=50, verbose_name='Cycle')),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Section',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(choices=[(1, 'Premier semestre'), (2, 'Deuxième semestre')])),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ACTIF', 'Actif'), ('PUBLIE', 'Publié'), ('ARCHIVE', 'Archivé')], default='BROUILLON', max_length=20)),
                ('repechage_actif', models.BooleanField(default=False, verbose_name='Repêchage actif')),
                ('date_activation', models.DateTimeField(blank=True, null=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('date_archivage', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='classes.anneescolaire')),
            ],
            options={
                'verbose_name': 'Classe',
                'ordering': ['niveau__ordre', 'nom', 'section__nom'],
            },
        ),
        migrations.CreateModel(
            name='DecisionPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('ADMIS', 'Admis — Promotion'), ('REDOUBLE', 'Redouble'), ('TRANSFERE', 'Transféré'), ('DIPLOME', 'Diplômé / Fin de cycle')], default='ADMIS', max_length=20)),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('validee', models.BooleanField(default=False, verbose_name='Validée')),
                ('date_decision', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions_promotion', to='classes.anneescolaire')),
                ('classe_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_arrivee', to='classes.classe', verbose_name='Classe de destination')),
                ('classe_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_depart', to='classes.classe', verbose_name="Classe d'origine")),
                ('decidee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Décision de promotion',
                'verbose_name_plural': 'Décisions de promotion',
                'ordering': ['eleve__nom', 'eleve__postnom'],
            },
        ),
    ]
