# Generated by Django 6.0.7 on 2026-07-26 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionpromotion',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions_promotion', to='students.student'),
        ),
        migrations.AddField(
            model_name='journaloperation',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_operations', to='classes.anneescolaire'),
        ),
        migrations.AddField(
            model_name='journaloperation',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='classes.niveau', verbose_name='Niveau'),
        ),
        migrations.AddField(
            model_name='classe',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='classes.section'),
        ),
        migrations.AddField(
            model_name='semestre',
            name='annee_scolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='classes.anneescolaire'),
        ),
        migrations.AddField(
            model_name='semestre',
            name='publie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semestres_publies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='decisionpromotion',
            unique_together={('eleve', 'annee_scolaire')},
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('nom', 'section', 'annee_scolaire')},
        ),
        migrations.AlterUniqueTogether(
            name='semestre',
            unique_together={('annee_scolaire', 'numero')},
        ),
    ]
