# Generated by Django 5.2.3 on 2026-07-26 22:10

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnuaireUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('schema_name', models.CharField(max_length=63)),
                ('type_compte', models.CharField(choices=[('admin_ecole', 'Admin Ecole'), ('prefet', 'Prefet'), ('enseignant', 'Enseignant')], max_length=20)),
            ],
            options={
                'verbose_name': 'Annuaire utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'ecole")),
                ('contact_nom', models.CharField(blank=True, max_length=200, verbose_name='Nom du responsable')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('contact_telephone', models.CharField(blank=True, max_length=50, verbose_name='Telephone')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(default='RDC', max_length=100, verbose_name='Pays')),
                ('date_debut_abonnement', models.DateField(blank=True, null=True, verbose_name='Debut abonnement')),
                ('date_fin_abonnement', models.DateField(blank=True, null=True, verbose_name='Fin abonnement')),
                ('jours_grace', models.IntegerField(default=7, verbose_name='Jours de grace')),
                ('statut', models.CharField(choices=[('active', 'Active'), ('suspendue', 'Suspendue'), ('expiree', 'Expiree'), ('corbeille', 'Corbeille')], db_index=True, default='active', max_length=20)),
                ('onboarding_complete', models.BooleanField(default=False, verbose_name='Configuration terminee')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ecole',
                'verbose_name_plural': 'Ecoles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du plan')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('max_eleves', models.IntegerField(default=150, verbose_name='Max eleves')),
                ('max_enseignants', models.IntegerField(default=30, verbose_name='Max enseignants')),
                ('max_classes', models.IntegerField(default=15, verbose_name='Max classes')),
                ('max_utilisateurs', models.IntegerField(default=35, verbose_name='Max utilisateurs')),
                ('prix_mensuel', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix mensuel (USD)')),
                ('is_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'verbose_name_plural': "Plans d'abonnement",
                'ordering': ['prix_mensuel'],
            },
        ),
        migrations.CreateModel(
            name='AdminEcole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('nom', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='Prenom')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='Telephone')),
                ('onboarding_step', models.IntegerField(default=0, verbose_name='Etape onboarding')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Derniere connexion')),
                ('ecole', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='tenants.ecole')),
            ],
            options={
                'verbose_name': "Administrateur d'ecole",
                'verbose_name_plural': "Administrateurs d'ecole",
            },
        ),
        migrations.CreateModel(
            name='EcoleDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.ecole')),
            ],
        ),
        migrations.CreateModel(
            name='ModeMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(blank=True, help_text='Ex: bulletins. Vide = tous les modules.', max_length=50)),
                ('is_active', models.BooleanField(default=False, verbose_name='Actif')),
                ('message', models.TextField(default='Le systeme est en maintenance. Veuillez reessayer plus tard.')),
                ('is_urgence', models.BooleanField(default=False, verbose_name='Urgence')),
                ('debut_prevu', models.DateTimeField(blank=True, null=True, verbose_name='Debut prevu')),
                ('fin_prevue', models.DateTimeField(blank=True, null=True, verbose_name='Fin prevue')),
                ('duree_estimee_minutes', models.IntegerField(default=60, verbose_name='Duree estimee (min)')),
                ('notification_envoyee', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('ecole', models.ForeignKey(blank=True, help_text='Null = maintenance globale', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.ecole')),
            ],
            options={
                'verbose_name': 'Mode maintenance',
            },
        ),
        migrations.AddField(
            model_name='ecole',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ecoles', to='tenants.planabonnement'),
        ),
    ]
