# Generated by Django 6.0.7 on 2026-07-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_annonceplateforme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annuaireutilisateur',
            name='type_compte',
            field=models.CharField(choices=[('admin_ecole', 'Admin Ecole'), ('prefet', 'Prefet'), ('enseignant', 'Enseignant'), ('secretariat', 'Secrétariat')], max_length=20),
        ),
    ]
