# Generated by Django 6.0.7 on 2026-07-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=255, verbose_name='Mot de passe (hache)')),
                ('nom', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='Prenom')),
                ('is_active', models.BooleanField(default=True)),
                ('totp_secret', models.CharField(blank=True, max_length=100)),
                ('totp_enabled', models.BooleanField(default=False, verbose_name='2FA active')),
                ('totp_recovery_codes', models.TextField(blank=True, default='[]')),
                ('must_change_password', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Derniere connexion')),
            ],
            options={
                'verbose_name': 'Super-Administrateur',
            },
        ),
    ]
