# Generated by Django 6.0.7 on 2026-07-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0002_platformsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='smtp_actif',
            field=models.BooleanField(default=False, verbose_name="Activer l'envoi SMTP réel"),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='smtp_from_email',
            field=models.CharField(blank=True, default='noreply@sgn-rdc.local', max_length=200, verbose_name="Adresse d'expédition (From)"),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='smtp_host',
            field=models.CharField(blank=True, default='', help_text='Ex: smtp.gmail.com, smtp.office365.com', max_length=200, verbose_name='Serveur SMTP'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='smtp_password',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Mot de passe SMTP'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587, verbose_name='Port SMTP'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, verbose_name='Utiliser TLS'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='smtp_user',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Identifiant SMTP'),
        ),
    ]
