# Generated by Django 6.0.7 on 2026-08-03 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0005_superadmin_photo_platform_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='site_logo',
            field=models.FileField(blank=True, help_text="PNG, JPG, GIF, SVG ou WEBP recommandé. Le logo s'affiche dans la barre latérale, la page de connexion et les en-têtes d'e-mails.", null=True, upload_to='platform/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'svg', 'webp'])], verbose_name='Logo plateforme'),
        ),
    ]
