# Generated by Django 6.0.7 on 2026-08-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0006_alter_platformsettings_site_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='public_bg_image',
            field=models.ImageField(blank=True, help_text='Image de fond utilisée sur les pages publiques Rejoindre et Inscription.', null=True, upload_to='platform/public/', verbose_name='Image de fond publique'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='public_page_bg_color',
            field=models.CharField(default='#0d0b2e', help_text="Couleur unie affichée sur les pages publiques lorsque aucune image de fond n'est configurée.", max_length=7, verbose_name='Couleur de fond publique'),
        ),
    ]
