# Generated by Django 6.0.7 on 2026-08-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0007_platformsettings_public_bg_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='public_bg_image_inscription',
            field=models.ImageField(blank=True, help_text="Image de fond utilisée sur le formulaire d'inscription. Remplace l'image publique par défaut si elle est définie.", null=True, upload_to='platform/public/', verbose_name='Image de fond page Inscription'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='public_bg_image_rejoindre',
            field=models.ImageField(blank=True, help_text="Image de fond utilisée sur la page Rejoindre. Remplace l'image publique par défaut si elle est définie.", null=True, upload_to='platform/public/', verbose_name='Image de fond page Rejoindre'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='public_bg_image',
            field=models.ImageField(blank=True, help_text="Image de fond par défaut utilisée quand aucune image spécifique à une page publique n'est configurée.", null=True, upload_to='platform/public/', verbose_name='Image de fond publique'),
        ),
    ]
