# Generated by Django 6.0.7 on 2026-08-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0008_platformsettings_public_bg_image_inscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='contact_adresse',
            field=models.TextField(blank=True, help_text='Adresse physique affichée sur la page Contact.', verbose_name='Adresse de contact'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='contact_whatsapp',
            field=models.CharField(blank=True, help_text='Numéro WhatsApp au format international, ex. +243123456789.', max_length=32, verbose_name='WhatsApp'),
        ),
    ]
