# Generated by Django 6.0.7 on 2026-08-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0009_platformsettings_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='facebook_url',
            field=models.URLField(blank=True, default='', verbose_name='Lien Facebook'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='linkedin_url',
            field=models.URLField(blank=True, default='', verbose_name='Lien LinkedIn'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='twitter_url',
            field=models.URLField(blank=True, default='', verbose_name='Lien Twitter / X'),
        ),
    ]
