# Generated by Django 6.0.7 on 2026-07-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin_ecole', "Administrateur d'ecole"), ('prefet', 'Prefet des etudes'), ('enseignant', 'Enseignant'), ('secretariat', 'Secrétariat'), ('comptable', 'Comptable')], db_index=True, default='enseignant', max_length=20),
        ),
    ]
