# Generated by Django 6.0.7 on 2026-07-30 17:50

import abonnement.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        ('students', '0002_add_tuteur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant payé')),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de paiement')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement bancaire')], default='especes', max_length=20, verbose_name='Mode de paiement')),
                ('reference', models.CharField(default=abonnement.models._generer_reference, editable=False, max_length=20, unique=True, verbose_name='Référence')),
                ('comptable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements_encaisses', to=settings.AUTH_USER_MODEL, verbose_name='Comptable')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='students.student', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=30, unique=True, verbose_name='Numéro de facture')),
                ('date_emission', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'émission")),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='abonnement.paiement', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='TypeFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(blank=True, help_text='Laisser vide pour appliquer à tous les élèves.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types_frais', to='classes.classe', verbose_name='Classe (optionnel)')),
            ],
            options={
                'verbose_name': 'Type de frais',
                'verbose_name_plural': 'Types de frais',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='paiement',
            name='type_frais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='abonnement.typefrais', verbose_name='Type de frais'),
        ),
    ]
