# Generated by Django 6.0.7 on 2026-07-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte_eleve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteconfig',
            name='modele',
            field=models.CharField(choices=[('classique', 'Classique'), ('moderne', 'Moderne'), ('institutionnel', 'Institutionnel'), ('minimaliste', 'Minimaliste'), ('premium', 'Premium'), ('horizon', 'Horizon'), ('congo', 'Congo'), ('emeraude', 'Emeraude'), ('crepuscule', 'Crépuscule')], default='classique', max_length=20, verbose_name='Modèle de carte'),
        ),
    ]
