# Generated by Django 6.0.7 on 2026-07-28 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nom_parent',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom du parent/tuteur (ancien)'),
        ),
        migrations.CreateModel(
            name='Tuteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('postnom', models.CharField(blank=True, max_length=100, verbose_name='Postnom')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Tuteur',
                'verbose_name_plural': 'Tuteurs',
                'ordering': ['nom', 'postnom'],
                'indexes': [models.Index(fields=['nom', 'postnom'], name='tuteur_nom_idx')],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='tuteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants', to='students.tuteur', verbose_name='Tuteur'),
        ),
    ]
