# Generated by Django 5.2.3 on 2026-07-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Institut Bungulu', max_length=200)),
                ('province', models.CharField(default='Nord-Kivu', max_length=100)),
                ('ville', models.CharField(default='Beni', max_length=100)),
                ('commune', models.CharField(default='Bungulu', max_length=100)),
                ('code', models.CharField(default='62024 / 101 / 03 / 1', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/')),
                ('pwa_nom', models.CharField(default='Système de Gestion Scolaire', max_length=200, verbose_name='Nom complet (PWA système)')),
                ('pwa_nom_court', models.CharField(default='SGS', max_length=30, verbose_name='Nom court (PWA système)')),
                ('pwa_description', models.CharField(default='Plateforme de gestion scolaire.', max_length=300, verbose_name='Description (PWA système)')),
                ('portail_pwa_nom', models.CharField(default='Portail Parent', max_length=200, verbose_name='Nom complet (PWA portail parent)')),
                ('portail_pwa_nom_court', models.CharField(default='Parent', max_length=30, verbose_name='Nom court (PWA portail parent)')),
                ('portail_pwa_description', models.CharField(default='Consultation des résultats scolaires, bulletins et informations des élèves.', max_length=300, verbose_name='Description (PWA portail parent)')),
                ('theme_color', models.CharField(default='#1E293B', max_length=7, verbose_name='Couleur principale (theme_color)')),
                ('background_color', models.CharField(default='#0f172a', max_length=7, verbose_name="Couleur d'arrière-plan (background_color)")),
            ],
            options={
                'verbose_name': "Informations de l'école",
            },
        ),
    ]
