# Generated by Django 6.0.7 on 2026-07-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='annee_scolaire_actuelle',
            field=models.CharField(blank=True, default='', help_text='Ex : 2025-2026', max_length=20, verbose_name='Année scolaire en cours'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='email_contact',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email de contact'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='type_etablissement',
            field=models.CharField(blank=True, choices=[('', '— Sélectionner —'), ('ep', 'École Primaire'), ('college', 'Collège'), ('institut', 'Institut (Humanités générales)'), ('lyceé', 'Lycée technique'), ('athénée', 'Athénée'), ('ecole_prof', 'École professionnelle'), ('complexe', 'Complexe scolaire'), ('autre', 'Autre')], default='institut', max_length=30, verbose_name="Type d'établissement"),
        ),
    ]
