# Generated by Django 6.0.7 on 2026-08-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_settings', '0004_matriculeconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculeconfig',
            name='annee_reference',
            field=models.CharField(blank=True, default='', help_text='Année scolaire en cours lors du dernier incrément (gestion du reset annuel).', max_length=4, verbose_name='Année de référence du compteur'),
        ),
        migrations.AlterField(
            model_name='matriculeconfig',
            name='compteur',
            field=models.PositiveIntegerField(default=0, help_text='Incrémenté automatiquement à chaque inscription. Modifiable pour reprendre une numérotation existante.', verbose_name='Compteur actuel'),
        ),
    ]
