# Generated by Django 5.2.3 on 2026-07-26 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bulletin', '0001_initial'),
        ('classes', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelebulletin',
            name='annee_scolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.anneescolaire'),
        ),
        migrations.AddField(
            model_name='modelebulletin',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles_bulletin', to='classes.classe'),
        ),
        migrations.AddField(
            model_name='modelebulletinmatiere',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.matiere'),
        ),
        migrations.AddField(
            model_name='modelebulletinmatiere',
            name='modele',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='bulletin.modelebulletin'),
        ),
        migrations.AlterUniqueTogether(
            name='modelebulletin',
            unique_together={('classe', 'annee_scolaire')},
        ),
        migrations.AlterUniqueTogether(
            name='modelebulletinmatiere',
            unique_together={('modele', 'matiere')},
        ),
    ]
