# Generated by Django 6.0.7 on 2026-07-27 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnoncePlateforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=180, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('type_annonce', models.CharField(choices=[('info', 'Information'), ('success', 'Bonne nouvelle'), ('warning', 'Important'), ('urgent', 'Urgent')], default='info', max_length=20, verbose_name='Type')),
                ('publiee', models.BooleanField(default=True, verbose_name='Publiée')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('date_expiration', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('auteur_nom', models.CharField(blank=True, max_length=150, verbose_name='Auteur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ecole', models.ForeignKey(blank=True, help_text='Vide = toutes les écoles', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annonces_plateforme', to='tenants.ecole')),
            ],
            options={
                'verbose_name': 'Annonce plateforme',
                'verbose_name_plural': 'Annonces plateforme',
                'ordering': ['-date_publication', '-created_at'],
            },
        ),
    ]
