# Generated by Django 6.0.7 on 2026-07-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_plan_abonnement_enriched_abonnement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annuaireutilisateur',
            name='type_compte',
            field=models.CharField(choices=[('admin_ecole', 'Admin Ecole'), ('prefet', 'Prefet'), ('enseignant', 'Enseignant'), ('secretariat', 'Secrétariat'), ('comptable', 'Comptable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='statut',
            field=models.CharField(choices=[('active', 'Active'), ('suspendue', 'Suspendue'), ('expiree', 'Expirée'), ('corbeille', 'Corbeille')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='planabonnement',
            name='max_eleves',
            field=models.IntegerField(default=150, verbose_name='Max élèves'),
        ),
    ]
