# Generated by Django 6.0.7 on 2026-07-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publie', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Modèle de bulletin',
                'verbose_name_plural': 'Modèles de bulletins',
                'ordering': ['-annee_scolaire__annee', 'classe__nom'],
            },
        ),
        migrations.CreateModel(
            name='ModeleBulletinMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Matière du bulletin',
                'ordering': ['matiere__maxima', 'ordre'],
            },
        ),
    ]
